"""Consortium identities and declared lineage; no identity inference from filenames."""
from __future__ import annotations

import re
import uuid
from datetime import datetime
from catalyst_ingest.readers import InputError

LABS = {
    'astar': ('ASTAR', 'A*STAR'),
    'slac': ('SLAC', 'SLAC'),
    'virginia-tech': ('VT', 'VA Tech (computational)'),
    'oxeon': ('OXEON', 'Oxeon (pilot scale)'),
    'northwestern': ('NU', 'Northwestern'),
    'university-of-rochester': ('UR', 'Rochester'),
}
LAB_CHOICES = tuple(name for _, name in LABS.values())
ALIASES = {v.casefold(): key for key, (code, name) in LABS.items() for v in (key, code, name)}
ALIASES.update({'va tech': 'virginia-tech', 'virginia tech': 'virginia-tech', 'oxeon': 'oxeon'})
KINDS = ('BAT', 'SYN', 'SMP', 'DS', 'MDL', 'PRC')
MATERIAL_KINDS = ('batch material', 'aliquot', 'treated material')
MODEL_RELATIONS = ('no physical link', 'represents', 'derived from', 'compared with')

TRACE_COMMON = {
    'datasetId': 'Canonical dataset ID',
    'submittingLab': 'Submitting lab',
    'acquisitionLab': 'Measurement / calculation lab',
    'processingLab': 'Processing lab',
    'localSampleId': 'Sample / model label in these source files',
    'methodId': 'Measurement / calculation method ID',
    'methodVersion': 'Measurement / calculation method version',
}
PHYSICAL_CONTEXT = {
    'batchId': 'Canonical synthesis batch ID',
    'originLab': 'Lab that synthesized the batch',
    'localBatchId': 'Origin lab’s batch label',
    'procedureId': 'Shared synthesis procedure ID',
    'procedureVersion': 'Shared synthesis procedure version',
    'procedureReference': 'Shared procedure document / SciSure protocol reference',
    'synthesisExecutionId': 'Canonical synthesis execution ID',
    'synthesizedAt': 'Synthesis date (YYYY-MM-DD)',
    'synthesisRecord': 'Actual synthesis record / ELN reference',
    'synthesisDeviations': 'Deviations from procedure (enter none if none)',
    'sampleCreatedLab': 'Lab that created this sample / aliquot',
    'materialKind': 'Material relationship',
    'parentSampleId': 'Parent sample ID (required for aliquot / treated material)',
    'materialState': 'Material state / treatment record',
    'custodyFromLab': 'Sending lab (if transferred)',
    'custodySampleId': 'ID of transferred sample (this sample or its parent)',
    'custodyRecord': 'Shipment / handoff record (if transferred)',
    'receivedAt': 'Receipt date (YYYY-MM-DD, if transferred)',
}
COMPUTATIONAL_CONTEXT = {
    'modelCreatedLab': 'Lab that created this model',
    'modelDescription': 'Model composition, structure, and representation',
    'modelRelation': 'Relationship to physical sample(s)',
    'relatedSampleIds': 'Related canonical sample IDs (comma separated)',
    'modelLinkEvidence': 'Basis for the model–sample relationship',
}


def lab_id(value):
    try:
        return ALIASES[value.strip().casefold()]
    except (KeyError, AttributeError):
        raise InputError('Choose one of the six consortium laboratories.') from None


def lab_name(value):
    return LABS[lab_id(value)][1]


def new_id(lab, kind):
    if kind not in KINDS:
        raise InputError('Unsupported identity type.')
    return f'CAT-{LABS[lab_id(lab)][0]}-{kind}-{uuid.uuid4().hex}'


def identity_lab(value, kind):
    for lab, (code, _) in LABS.items():
        if re.fullmatch(r'CAT-' + code + '-' + kind + r'-[0-9a-f]{32}', value or ''):
            return lab
    raise InputError(f'Use a CATALYST {kind} identifier generated by the app; keep local labels separately.')


def trace_context(modality):
    return TRACE_COMMON | (COMPUTATIONAL_CONTEXT if modality == 'computational' else PHYSICAL_CONTEXT)


def date_value(value):
    if not isinstance(value, str) or not re.fullmatch(r'\d{4}-\d{2}-\d{2}', value):
        raise ValueError('Use YYYY-MM-DD.')
    return datetime.strptime(value, '%Y-%m-%d')


def build_traceability(entity, modality, context, artifacts=()):
    """Return structured declarations plus blocking issues for incomplete identity context."""
    from .workflow import is_workflow, build_workflow_trace
    if is_workflow(context):
        return build_workflow_trace(entity, modality, context, artifacts)
    issues = []
    def error(code, text):
        issues.append(dict(code=code, message=text, severity='error'))
    def required(key):
        value = context.get(key, '').strip()
        if not value:
            error('TRACE_' + key, (trace_context(modality).get(key) or key) + ' is required.')
        return value
    def lab(key):
        try:
            return lab_id(required(key))
        except InputError:
            error('LAB_' + key, 'Choose a registered consortium laboratory for ' + key + '.')
            return None
    def identifier(key, kind, expected_lab=None):
        value = required(key)
        try:
            actual = identity_lab(value, kind)
            if expected_lab and actual != expected_lab:
                error('ID_LAB_' + key, key + ' belongs to a different creating lab. Do not relabel an existing ID.')
        except InputError as e:
            error('ID_' + key, str(e))
        return value
    acq, processing = lab('acquisitionLab'), lab('processingLab')
    dataset_id = identifier('datasetId', 'DS', acq)
    alias = required('localSampleId')
    method = dict(id=required('methodId'), version=required('methodVersion'))
    trace = dict(schema_version='catalyst-traceability/1', lab_registry_version=1,
        source_lab=lab_id(entity), submitting_lab=lab('submittingLab'), processing_lab=processing,
        dataset=dict(id=dataset_id, acquisition_lab=acq, local_id=required('runId'),
            acquired_by=required('acquiredBy'), acquired_at=required('acquiredAt'), method=method),
        aliases=[], custody_evidence=None)
    if modality == 'computational':
        creator = lab('modelCreatedLab')
        mid = identifier('specimenId', 'MDL', creator)
        relation = required('modelRelation')
        linked = [v.strip() for v in context.get('relatedSampleIds', '').split(',') if v.strip()]
        if len(linked) > 20 or len(set(linked)) != len(linked):
            error('MODEL_LINKS', 'Use at most 20 distinct related sample IDs.')
        for item in linked:
            try: identity_lab(item, 'SMP')
            except InputError as e: error('MODEL_SAMPLE_ID', str(e))
        if relation not in MODEL_RELATIONS or (relation == 'no physical link') != (not linked):
            error('MODEL_RELATION', 'Declare no physical link, or choose a relationship and provide the linked sample IDs.')
        evidence = required('modelLinkEvidence') if linked else context.get('modelLinkEvidence', '')
        trace['model'] = dict(id=mid, creator_lab=creator, description=required('modelDescription'), input_structure=required('inputStructure'),
            physical_relation=relation, related_sample_ids=linked, link_evidence=evidence)
        trace['dataset'].update(kind='computation', subject_id=mid)
        trace['aliases'].append(dict(lab=lab_id(entity), local_label=alias, canonical_id=mid))
    else:
        origin, creator = lab('originLab'), lab('sampleCreatedLab')
        bid = identifier('batchId', 'BAT', origin)
        sid = identifier('specimenId', 'SMP', creator)
        synth = identifier('synthesisExecutionId', 'SYN', origin)
        parent = context.get('parentSampleId', '')
        kind = required('materialKind')
        if kind not in MATERIAL_KINDS:
            error('MATERIAL_KIND', 'Choose batch material, aliquot, or treated material.')
        if kind == 'batch material':
            if parent or creator != origin:
                error('ROOT_MATERIAL', 'Batch material must be created at the synthesis lab and have no parent. Use aliquot or treated material for a derivative.')
        elif not parent:
            error('PARENT_REQUIRED', 'An aliquot or treated material needs its canonical parent sample ID.')
        if parent:
            try: identity_lab(parent, 'SMP')
            except InputError as e: error('PARENT_ID', str(e))
            if parent == sid:
                error('SELF_PARENT', 'A sample cannot be its own parent.')
        synthesized = required('synthesizedAt')
        try:
            if date_value(synthesized) > date_value(context.get('acquiredAt', '')):
                error('SYNTHESIS_DATE', 'Synthesis cannot be later than this acquisition.')
        except ValueError:
            error('SYNTHESIS_DATE', 'Synthesis and acquisition dates must use YYYY-MM-DD.')
        trace['batch'] = dict(id=bid, origin_lab=origin, local_id=required('localBatchId'),
            procedure=dict(id=required('procedureId'), version=required('procedureVersion'), reference=required('procedureReference')),
            synthesis_execution=dict(id=synth, lab=origin, record=required('synthesisRecord'),
                performed_at=synthesized, deviations=required('synthesisDeviations')))
        trace['material'] = dict(id=sid, batch_id=bid, creator_lab=creator, kind=kind,
            parent_sample_id=parent or None, state=required('materialState'))
        trace['dataset'].update(kind='synthesis' if modality == 'synthesis' else 'measurement', subject_id=sid)
        trace['aliases'].append(dict(lab=lab_id(entity), local_label=alias, canonical_id=sid))
        if modality == 'synthesis' and acq != origin:
            error('SYNTHESIS_LAB', 'A synthesis execution must be attributed to the lab that made the batch. Submitting or processing labs can differ.')
        transferred = any(context.get(k) for k in ('custodyFromLab', 'custodySampleId', 'custodyRecord', 'receivedAt'))
        if creator != acq or transferred:
            sender = lab('custodyFromLab')
            received = required('receivedAt')
            record = required('custodyRecord')
            if sender == acq:
                error('CUSTODY_LABS', 'Sending and receiving laboratories must differ.')
            try:
                receipt_date = date_value(received)
                acquisition_date = date_value(context.get('acquiredAt', ''))
                if receipt_date > acquisition_date:
                    error('CUSTODY_DATE', 'The sample cannot be received after this acquisition.')
                if receipt_date < date_value(synthesized):
                    error('CUSTODY_DATE', 'The sample cannot be received before its batch was synthesized.')
            except ValueError:
                error('CUSTODY_DATE', 'Receipt and acquisition dates must use YYYY-MM-DD.')
            moved_id = context.get('custodySampleId') or sid
            if moved_id not in (sid, parent) or (creator != acq and moved_id != sid):
                error('CUSTODY_SAMPLE', 'Handoff evidence must identify this sample, or its parent when preparing a derivative at the receiving lab.')
            trace['custody_evidence'] = dict(sample_id=moved_id, from_lab=sender, to_lab=acq,
                received_at=received, record=record, basis='contributor-declared handoff; not live location tracking')
    trace['dataset']['modality'] = modality
    return trace, issues


def attach_subject(preview):
    """Bind every measurement row to the declared subject; never silently merge labels."""
    trace = preview['traceability']
    sid = trace['dataset']['subject_id']
    aliases = {a['local_label'] for a in trace['aliases'] if a['lab'] == trace['source_lab']}
    mismatches = []
    for row in preview['standardized'].get('rows', []):
        supplied = [row.get('specimen_id'), row.get('model_id')]
        if any(value is not None and value != sid and value not in aliases for value in supplied):
            mismatches.append(row.get('source_row', '?'))
        row['canonical_subject_id'] = sid
        row['canonical_dataset_id'] = trace['dataset']['id']
    if mismatches:
        preview['validation']['issues'].append(dict(code='SUBJECT_MISMATCH', severity='error',
            message='Mapped sample/model labels do not match the declared ID or exact source-lab alias '
                f'(rows {mismatches[:10]}). Split multiple samples into separate submissions or correct the explicit mapping.'))
    return preview


def identity_records(trace):
    """Immutable identity definitions used for conflict checks across saved reviews."""
    records = {trace['dataset']['id']: trace['dataset']}
    for key in ('batch', 'material', 'model'):
        if key in trace:
            records[trace[key]['id']] = trace[key]
    if 'procedure' in trace:
        procedure = trace['procedure']
        records[procedure['id'] + '@' + procedure['version']] = procedure
    if 'synthesis_execution' in trace:
        records[trace['synthesis_execution']['id']] = trace['synthesis_execution']
    if 'batch' in trace:
        execution = trace['batch']['synthesis_execution']
        records[execution['id']] = dict(execution, batch_id=trace['batch']['id'])
    return records


def validate_catalog(incoming, saved):
    """Validate identities against complete saved packets in the active group."""
    records, aliases, procedures = {}, {}, {}
    saved_materials = {t['material']['id']: t['material'] for t in saved if 'material' in t}
    saved_procedures = {}
    for trace in saved:
        if 'procedure' in trace:
            procedure = trace['procedure']
            saved_procedures[(procedure['id'], procedure['version'])] = procedure
        elif 'batch' in trace:
            procedure = trace['batch']['procedure']
            saved_procedures.setdefault((procedure['id'], procedure['version']),
                dict(procedure, type='synthesis', modality='synthesis'))
    for trace in [*saved, incoming]:
        if 'batch' in trace:
            procedure = trace['batch']['procedure']
            key = procedure['id'], procedure['version']
            if key in procedures and procedures[key] != procedure:
                raise InputError('The shared procedure ID/version already points to a different document. Review the reference or use a new procedure version.')
            procedures[key] = procedure
        for key, value in identity_records(trace).items():
            if key in records and records[key] != value:
                raise InputError('An existing canonical ID has conflicting identity or lineage metadata: ' + key)
            records[key] = value
        for alias in trace['aliases']:
            key = alias['lab'], alias['local_label']
            aliases.setdefault(key, set()).add(alias['canonical_id'])
    subject = incoming.get('material')
    if subject and subject['kind'] == 'batch material':
        if any(t.get('material', {}).get('batch_id') == subject['batch_id']
                and t['material']['kind'] == 'batch material' and t['material']['id'] != subject['id'] for t in saved):
            raise InputError('This batch already has a root sample. Reuse it or register a linked aliquot instead.')
    if subject and subject.get('parent_sample_id'):
        parent = saved_materials.get(subject['parent_sample_id'])
        if not parent or ('batch_id' in subject and parent.get('batch_id') != subject['batch_id']):
            raise InputError('The parent sample must already be registered in this group and belong to the same batch.')
        if 'batch_id' in subject and parent['creator_lab'] != subject['creator_lab']:
            receipts = [t.get('custody_evidence') for t in [*saved, incoming]]
            if not any(r and r['sample_id'] == parent['id'] and r['to_lab'] == subject['creator_lab'] for r in receipts):
                raise InputError('Record the parent sample’s handoff to the lab creating this derivative before publishing.')
        visited = {subject['id']}
        while parent:
            if parent['id'] in visited:
                raise InputError('Sample lineage contains a cycle.')
            visited.add(parent['id'])
            parent = records.get(parent.get('parent_sample_id'))
    for linked in incoming.get('model', {}).get('related_sample_ids', []):
        if linked not in saved_materials:
            raise InputError('A model-linked physical sample must already be registered in this group: ' + linked)
    if incoming.get('schema_version') == 'catalyst-traceability/2':
        kind = incoming.get('record_type')
        if kind in ('measurement', 'synthesis'):
            sample = incoming.get('sample_ref', {}).get('id')
            if sample != incoming['dataset'].get('subject_id') or sample not in saved_materials:
                raise InputError('Select a completed, registered sample before saving this record.')
        unknown_method = (kind == 'measurement' and incoming['dataset'].get('method_status') == 'not-recorded'
            and incoming['dataset'].get('method') is None)
        if kind in ('measurement', 'synthesis', 'computation') and not unknown_method:
            method = incoming['dataset'].get('method') or {}
            procedure = saved_procedures.get((method.get('id'), method.get('version')))
            if not procedure:
                raise InputError('Select a completed saved procedure and version before saving this record.')
            if not (procedure.get('instructions') or procedure.get('reference') or procedure.get('artifact_sha256s')):
                raise InputError('The selected procedure has no registered instructions or document evidence.')
            if procedure.get('type') != kind:
                raise InputError('The selected procedure type does not match this record type.')
            if procedure.get('modality') != incoming['dataset'].get('modality'):
                raise InputError('The selected procedure technique does not match this data type.')
    # Local aliases are deliberately not globally unique; canonical IDs remain authoritative.
    return [dict(lab=lab, local_label=label, canonical_ids=sorted(ids))
        for (lab, label), ids in aliases.items() if len(ids) > 1]
